use_frameworks!

platform :ios, '9.0'

target 'LeetCode_Example' do
  pod 'LeetCode', :path => '../'

  target 'LeetCode_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
